stages:
  - test
  - deploy

tests-on-ubuntu-20.04:
  stage: test
  only:
    - devel
    - /^devel-.*/
  # except: # MG20220815: Keep this for memory
  #   - PreOperators # MG20220413: this branch is outdated
  #   - CylindricalModel # MG20211221: this branch is outdated
  tags:
    - ci.inria.fr
    - large
  image: ubuntu:20.04
  # image: quay.io/fenicsproject/stable:latest # MG20211221: somehow this does not work
  # image: python $ MG20211221: this seems to be debian not ubuntu, which is necessary for ppa install
  script:
    # - uname -a
    # - conda env list # MG20211221: conda not available in python image
    - apt update; apt upgrade -y
    - apt update; DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris apt install -y git gnuplot python3-matplotlib python3-numpy python3-pandas python3-pip python-is-python3 # MG20220814: environment variables are needed to prevent tzdata installation hanging while waiting timezone info, cf. https://anonoz.github.io/tech/2020/04/24/docker-build-stuck-tzdata.html
    - apt update; apt install -y software-properties-common; add-apt-repository -y ppa:fenics-packages/fenics; apt update; apt install -y fenics; export DISPLAY=0:0
#     - apt update; apt install -y libopenblas-base; export OMP_NUM_THREADS="1" # MG20221201: This seems to fail in ubuntu 20.04
    - apt update; apt install -y libvtk7-dev python3-vtk7; export CPATH="/usr/include/vtk-7.1":$CPATH
    - apt update; apt install -y libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxft-dev libxinerama1 gcc-multilib xvfb gmsh; pip install gmsh
    - apt update; apt install -y python3-h5py; pip install meshio; pip install --upgrade numpy # MG20220814: meshio needs latest numpy apparently
    - pip install numpy==1.23.5 # MG20230103: apparently numpy >= 1.24 does not work anymore with the old version of pandas (and probably other stuff) present in Ubuntu 20.04 apt repo, cf. https://stackoverflow.com/a/74975994
    - pip install git+https://gitlab.inria.fr/mgenet/myPythonLibrary.git
    - pip install git+https://gitlab.inria.fr/mgenet/myVTKPythonLibrary.git
    - cd Tests; ln -s ../dolfin_mech; make

tests-on-ubuntu-22.04:
  stage: test
  only:
    - devel
    - /^devel-.*/
  tags:
    - ci.inria.fr
    - large
  image: ubuntu:22.04
  script:
    - apt update; apt upgrade -y
    - apt update; DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris apt install -y git gnuplot python3-matplotlib python3-numpy python3-pandas python3-pip python-is-python3 # MG20220814: environment variables are needed to prevent tzdata installation hanging while waiting timezone info, cf. https://anonoz.github.io/tech/2020/04/24/docker-build-stuck-tzdata.html
    - apt update; apt install -y software-properties-common; add-apt-repository -y ppa:fenics-packages/fenics; apt update; apt install -y fenics; export DISPLAY=0:0
    - apt update; apt install -y libopenblas-base; export OMP_NUM_THREADS="1"
    - apt update; apt install -y libvtk9-dev python3-vtk9; export CPATH="/usr/include/vtk-9.1":$CPATH
    - apt update; apt install -y libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxft-dev libxinerama1 gcc-multilib xvfb gmsh; pip install gmsh
    - apt update; apt install -y python3-h5py; pip install meshio; pip install --upgrade numpy # MG20220814: meshio needs latest numpy apparently
    - pip install git+https://gitlab.inria.fr/mgenet/myPythonLibrary.git
    - pip install git+https://gitlab.inria.fr/mgenet/myVTKPythonLibrary.git
    - cd Tests; ln -s ../dolfin_mech; make

pypi:
  stage: deploy
  only:
    - master
  tags:
    - ci.inria.fr
    - small
  image: python
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

gitlab:
  stage: deploy
  only:
    - master
  tags:
    - ci.inria.fr
    - small
  image: python
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} twine upload --verbose --skip-existing --repository-url https://gitlab.inria.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
